# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9773d5c352517dd847d776c82289b4b606ec487e4b8aec79458eea5f69761afa887764730fdee2f421a083330159f85bb79a0cba73299d9803137a0d6c3a7cc

test:
  secret_key_base: 132b6038cc539e26277f4cfbf92ad2f0f6e7f36bdb0588b5a26318cc0dfba5975a11522c909910c2eaf7faf97c3acfe5c13fc72910af8f0c73b2b62abbb809ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
